# Generated by Django 2.2.12 on 2020-04-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_pg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name="ім'я автора")),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст коментаря')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post_Program')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.CreateModel(
            name='Comment_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name="ім'я автора")),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст коментаря')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post_Admin')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
