# Generated by Django 3.0.5 on 2020-04-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_ad_comment_pg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_ad',
            old_name='article',
            new_name='post_admin',
        ),
        migrations.RenameField(
            model_name='comment_pg',
            old_name='article',
            new_name='post_program',
        ),
    ]
